//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModernApplicationFramework.WindowManagement.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WindowManagement_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WindowManagement_Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModernApplicationFramework.WindowManagement.Properties.WindowManagement.Resources" +
                            "", typeof(WindowManagement_Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window layout &quot;{0}&quot; successfully applied..
        /// </summary>
        public static string ApplyLayoutCompletedStatusFormat {
            get {
                return ResourceManager.GetString("ApplyLayoutCompletedStatusFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to apply the layout &apos;{0}&apos; and discard your current window layout?.
        /// </summary>
        public static string ApplyLayoutConfirmation {
            get {
                return ResourceManager.GetString("ApplyLayoutConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not apply window layout &quot;{0}&quot;..
        /// </summary>
        public static string ApplyLayoutErrorStatusFormat {
            get {
                return ResourceManager.GetString("ApplyLayoutErrorStatusFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not apply layout &apos;{0}&apos;..
        /// </summary>
        public static string ApplyLayoutFailedMessage {
            get {
                return ResourceManager.GetString("ApplyLayoutFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applying window layout &quot;{0}&quot;....
        /// </summary>
        public static string ApplyLayoutStartedStatusFormat {
            get {
                return ResourceManager.GetString("ApplyLayoutStartedStatusFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Window Layout.
        /// </summary>
        public static string ApplyLayoutTitle {
            get {
                return ResourceManager.GetString("ApplyLayoutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Window Layout {0}.
        /// </summary>
        public static string ApplyWindowLayoutCommantDefinition_Name {
            get {
                return ResourceManager.GetString("ApplyWindowLayoutCommantDefinition_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Window Layout List.
        /// </summary>
        public static string ApplyWindowLayoutListCommandDefinition_Name {
            get {
                return ResourceManager.GetString("ApplyWindowLayoutListCommandDefinition_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the layout &apos;{0}&apos;?.
        /// </summary>
        public static string DeleteLayoutConfirmation {
            get {
                return ResourceManager.GetString("DeleteLayoutConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Window Layout.
        /// </summary>
        public static string DeleteLayoutTitle {
            get {
                return ResourceManager.GetString("DeleteLayoutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Don&apos;t show me this message again.
        /// </summary>
        public static string DisableApplyLayoutWarning {
            get {
                return ResourceManager.GetString("DisableApplyLayoutWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A layout named &apos;{0}&apos; already exists.
        ///Do you want to replace it?.
        /// </summary>
        public static string LayoutOverwriteMessage {
            get {
                return ResourceManager.GetString("LayoutOverwriteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Window Layouts.
        /// </summary>
        public static string ManageLayoutCommandDefinition_Name {
            get {
                return ResourceManager.GetString("ManageLayoutCommandDefinition_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Manage Window Layouts.
        /// </summary>
        public static string ManageLayoutCommandDefinition_Text {
            get {
                return ResourceManager.GetString("ManageLayoutCommandDefinition_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string ManageLayoutsButton_Close {
            get {
                return ResourceManager.GetString("ManageLayoutsButton_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Delete.
        /// </summary>
        public static string ManageLayoutsButton_Delete {
            get {
                return ResourceManager.GetString("ManageLayoutsButton_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Rename.
        /// </summary>
        public static string ManageLayoutsButton_Rename {
            get {
                return ResourceManager.GetString("ManageLayoutsButton_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Down (Alt+Down).
        /// </summary>
        public static string ManageLayoutsButtonTooltip_IndexDown {
            get {
                return ResourceManager.GetString("ManageLayoutsButtonTooltip_IndexDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Up (Alt+Up).
        /// </summary>
        public static string ManageLayoutsButtonTooltip_IndexUp {
            get {
                return ResourceManager.GetString("ManageLayoutsButtonTooltip_IndexUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Saved layouts:.
        /// </summary>
        public static string ManageLayoutsDialogSavedLayouts {
            get {
                return ResourceManager.GetString("ManageLayoutsDialogSavedLayouts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Window Layouts.
        /// </summary>
        public static string ManageLayoutsDialogTitle {
            get {
                return ResourceManager.GetString("ManageLayoutsDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Window Layout.
        /// </summary>
        public static string MenuDefinition_ApplyLayout {
            get {
                return ResourceManager.GetString("MenuDefinition_ApplyLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Saved Layouts.
        /// </summary>
        public static string NoSavedLayouts {
            get {
                return ResourceManager.GetString("NoSavedLayouts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Layout name:.
        /// </summary>
        public static string RenameLayoutMessage {
            get {
                return ResourceManager.GetString("RenameLayoutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename Window Layout.
        /// </summary>
        public static string RenameLayoutTitle {
            get {
                return ResourceManager.GetString("RenameLayoutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Window Layout.
        /// </summary>
        public static string ResetLayoutCommandDefinition_Name {
            get {
                return ResourceManager.GetString("ResetLayoutCommandDefinition_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Reset Window Layout.
        /// </summary>
        public static string ResetLayoutCommandDefinition_Text {
            get {
                return ResourceManager.GetString("ResetLayoutCommandDefinition_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to restore the default window layout for the environment?.
        /// </summary>
        public static string ResetLayoutConfirmation {
            get {
                return ResourceManager.GetString("ResetLayoutConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Window Layout.
        /// </summary>
        public static string SaveLayoutCommandDefinition_Name {
            get {
                return ResourceManager.GetString("SaveLayoutCommandDefinition_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Save Window Layout.
        /// </summary>
        public static string SaveLayoutCommandDefinition_Text {
            get {
                return ResourceManager.GetString("SaveLayoutCommandDefinition_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Layout {0}.
        /// </summary>
        public static string SaveLayoutCommandDefinitionMessageBox_Default {
            get {
                return ResourceManager.GetString("SaveLayoutCommandDefinitionMessageBox_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Layout name:.
        /// </summary>
        public static string SaveLayoutCommandDefinitionMessageBox_Label {
            get {
                return ResourceManager.GetString("SaveLayoutCommandDefinitionMessageBox_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Window Layout.
        /// </summary>
        public static string SaveLayoutCommandDefinitionMessageBox_Title {
            get {
                return ResourceManager.GetString("SaveLayoutCommandDefinitionMessageBox_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window layout &quot;{0}&quot; successfully saved..
        /// </summary>
        public static string SaveLayoutCompletedStatusFormat {
            get {
                return ResourceManager.GetString("SaveLayoutCompletedStatusFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We could not save your layout. The total number of layouts reached maximum of {0}.
        ///
        ///Please delete one or more layouts before saving..
        /// </summary>
        public static string SaveLayoutErrorMaxLayoutsReached {
            get {
                return ResourceManager.GetString("SaveLayoutErrorMaxLayoutsReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not save window layout &quot;{0}&quot;..
        /// </summary>
        public static string SaveLayoutErrorStatusFormat {
            get {
                return ResourceManager.GetString("SaveLayoutErrorStatusFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Layout name:.
        /// </summary>
        public static string SaveLayoutMessage {
            get {
                return ResourceManager.GetString("SaveLayoutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving window layout &quot;{0}&quot;....
        /// </summary>
        public static string SaveLayoutStartedStatusFormat {
            get {
                return ResourceManager.GetString("SaveLayoutStartedStatusFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Window Layout.
        /// </summary>
        public static string SaveLayoutTitle {
            get {
                return ResourceManager.GetString("SaveLayoutTitle", resourceCulture);
            }
        }
    }
}
