//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModernApplicationFramework.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Commands_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Commands_Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModernApplicationFramework.Properties.Commands.Resources", typeof(Commands_Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Hide.
        /// </summary>
        public static string AutoHideWindowCommandDefinition_Text {
            get {
                return ResourceManager.GetString("AutoHideWindowCommandDefinition_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Category_Edit {
            get {
                return ResourceManager.GetString("Category_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string Category_File {
            get {
                return ResourceManager.GetString("Category_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string Category_Tools {
            get {
                return ResourceManager.GetString("Category_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string Category_View {
            get {
                return ResourceManager.GetString("Category_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window.
        /// </summary>
        public static string Category_Window {
            get {
                return ResourceManager.GetString("Category_Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close All But This.
        /// </summary>
        public static string CloseAllButThisDockedWindowCommandDefinition_Text {
            get {
                return ResourceManager.GetString("CloseAllButThisDockedWindowCommandDefinition_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close All Documents.
        /// </summary>
        public static string CloseAllDockedWindowCommandDefinition_Text {
            get {
                return ResourceManager.GetString("CloseAllDockedWindowCommandDefinition_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CloseDockedWindowCommandDefinition_Text {
            get {
                return ResourceManager.GetString("CloseDockedWindowCommandDefinition_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Customize....
        /// </summary>
        public static string CustomizeMenuCommandDefinition_Text {
            get {
                return ResourceManager.GetString("CustomizeMenuCommandDefinition_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dock as Tabbed Document.
        /// </summary>
        public static string DockAsTabbedDocumentCommandDefinition_Text {
            get {
                return ResourceManager.GetString("DockAsTabbedDocumentCommandDefinition_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dock.
        /// </summary>
        public static string DockWindowCommandDefinition_Text {
            get {
                return ResourceManager.GetString("DockWindowCommandDefinition_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Float.
        /// </summary>
        public static string FloatDockedWindowCommandDefinition_Text {
            get {
                return ResourceManager.GetString("FloatDockedWindowCommandDefinition_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        public static string HideDockedWindowCommandDefinition_Text {
            get {
                return ResourceManager.GetString("HideDockedWindowCommandDefinition_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolbar List.
        /// </summary>
        public static string ListToolBarsCommandListDefinition_Name {
            get {
                return ResourceManager.GetString("ListToolBarsCommandListDefinition_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move All to Next Tab Group.
        /// </summary>
        public static string MoveAllToNextTabGroupCommandDefinition_Text {
            get {
                return ResourceManager.GetString("MoveAllToNextTabGroupCommandDefinition_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move All to Previous Tab Group.
        /// </summary>
        public static string MoveAllToPreviousTabGroupCommandDefinition_Text {
            get {
                return ResourceManager.GetString("MoveAllToPreviousTabGroupCommandDefinition_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to Next Tab Group.
        /// </summary>
        public static string MoveToNextTabGroupCommandDefinition_Text {
            get {
                return ResourceManager.GetString("MoveToNextTabGroupCommandDefinition_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to Previous Tab Group.
        /// </summary>
        public static string MoveToPreviousTabGroupCommandDefinition_Text {
            get {
                return ResourceManager.GetString("MoveToPreviousTabGroupCommandDefinition_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Horizontal Tab Group.
        /// </summary>
        public static string NewHorizontalTabGroupCommandDefinition_Text {
            get {
                return ResourceManager.GetString("NewHorizontalTabGroupCommandDefinition_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Vertical Tab Group.
        /// </summary>
        public static string NewVerticalTabGroupCommandDefinition_Text {
            get {
                return ResourceManager.GetString("NewVerticalTabGroupCommandDefinition_Text", resourceCulture);
            }
        }
    }
}
