//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModernApplicationFramework.Extended.Settings.SettingsImportExport {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SettingsImportExportResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SettingsImportExportResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModernApplicationFramework.Extended.Settings.SettingsImportExport.SettingsImportE" +
                            "xportResources", typeof(SettingsImportExportResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings files (*.mafsettings)|*.mafsettings|All files (*.*)|*.*.
        /// </summary>
        public static string SaveFileDialog_Filter {
            get {
                return ResourceManager.GetString("SaveFileDialog_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose an always saved settings file.
        /// </summary>
        public static string SaveFileDialog_Title {
            get {
                return ResourceManager.GetString("SaveFileDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B_rowse....
        /// </summary>
        public static string SaveFileDialogButton_Text {
            get {
                return ResourceManager.GetString("SaveFileDialogButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified path for the auto-save settings file is invalid. Please enter a valid path..
        /// </summary>
        public static string SelectedPathNull_Warning {
            get {
                return ResourceManager.GetString("SelectedPathNull_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Au_tomatically save my settings to this file:.
        /// </summary>
        public static string SettingsFilePathCombo_Label {
            get {
                return ResourceManager.GetString("SettingsFilePathCombo_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import and Export Settings.
        /// </summary>
        public static string SettingsImportExport_Name {
            get {
                return ResourceManager.GetString("SettingsImportExport_Name", resourceCulture);
            }
        }
    }
}
