//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModernApplicationFramework.WindowManagement.Options {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TabsWindowsOptions_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TabsWindowsOptions_Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModernApplicationFramework.WindowManagement.Options.TabsWindowsOptions.Resources", typeof(TabsWindowsOptions_Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Confirm before applying custom window layout ähnelt.
        /// </summary>
        public static string ApplyLayoutConfirmation {
            get {
                return ResourceManager.GetString("ApplyLayoutConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insert new tabs to the _right of existing tabs ähnelt.
        /// </summary>
        public static string DocumentDockPreference {
            get {
                return ResourceManager.GetString("DocumentDockPreference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Maintain pin status if document is removed from well ähnelt.
        /// </summary>
        public static string MaintainPinStatus {
            get {
                return ResourceManager.GetString("MaintainPinStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pinned Tabs ähnelt.
        /// </summary>
        public static string PinnedTabsGroup {
            get {
                return ResourceManager.GetString("PinnedTabsGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die S_how pin button in unpinned tabs ähnelt.
        /// </summary>
        public static string ShowPinButton {
            get {
                return ResourceManager.GetString("ShowPinButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Show pinned tabs in a separate row ähnelt.
        /// </summary>
        public static string ShowPinnedTabsInNewRow {
            get {
                return ResourceManager.GetString("ShowPinnedTabsInNewRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show auto-hidden _windows on mouse over ähnelt.
        /// </summary>
        public static string ShowToolsOnHover {
            get {
                return ResourceManager.GetString("ShowToolsOnHover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tabs and Windows ähnelt.
        /// </summary>
        public static string TabsAndWindowSettingsTitle {
            get {
                return ResourceManager.GetString("TabsAndWindowSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tab Well ähnelt.
        /// </summary>
        public static string TabWellGroup {
            get {
                return ResourceManager.GetString("TabWellGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tool Windows ähnelt.
        /// </summary>
        public static string ToolWindowsGroup {
            get {
                return ResourceManager.GetString("ToolWindowsGroup", resourceCulture);
            }
        }
    }
}
