//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModernApplicationFramework.WindowManagement.Options {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TabsWindowsOptions_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TabsWindowsOptions_Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModernApplicationFramework.WindowManagement.Options.TabsWindowsOptions.Resources", typeof(TabsWindowsOptions_Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Confirm before applying custom window layout.
        /// </summary>
        public static string ApplyLayoutConfirmation {
            get {
                return ResourceManager.GetString("ApplyLayoutConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert new tabs to the _right of existing tabs.
        /// </summary>
        public static string DocumentDockPreference {
            get {
                return ResourceManager.GetString("DocumentDockPreference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Maintain pin status if document is removed from well.
        /// </summary>
        public static string MaintainPinStatus {
            get {
                return ResourceManager.GetString("MaintainPinStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pinned Tabs.
        /// </summary>
        public static string PinnedTabsGroup {
            get {
                return ResourceManager.GetString("PinnedTabsGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_how pin button in unpinned tabs.
        /// </summary>
        public static string ShowPinButton {
            get {
                return ResourceManager.GetString("ShowPinButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Show pinned tabs in a separate row.
        /// </summary>
        public static string ShowPinnedTabsInNewRow {
            get {
                return ResourceManager.GetString("ShowPinnedTabsInNewRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show auto-hidden _windows on mouse over.
        /// </summary>
        public static string ShowToolsOnHover {
            get {
                return ResourceManager.GetString("ShowToolsOnHover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabs and Windows.
        /// </summary>
        public static string TabsAndWindowSettingsTitle {
            get {
                return ResourceManager.GetString("TabsAndWindowSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab Well.
        /// </summary>
        public static string TabWellGroup {
            get {
                return ResourceManager.GetString("TabWellGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool Windows.
        /// </summary>
        public static string ToolWindowsGroup {
            get {
                return ResourceManager.GetString("ToolWindowsGroup", resourceCulture);
            }
        }
    }
}
