//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModernApplicationFramework.Extended.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Commands_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Commands_Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModernApplicationFramework.Extended.Properties.Commands.Resources", typeof(Commands_Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E&amp;xit.
        /// </summary>
        internal static string CloseProgramCommandDefinition_Text {
            get {
                return ResourceManager.GetString("CloseProgramCommandDefinition_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F&amp;ull Screen.
        /// </summary>
        internal static string FullScreenCommandDefinition_Text {
            get {
                return ResourceManager.GetString("FullScreenCommandDefinition_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fensterlayouts verwalten.
        /// </summary>
        internal static string ManageLayoutCommandDefinition_Name {
            get {
                return ResourceManager.GetString("ManageLayoutCommandDefinition_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fensterlayouts &amp;verwalten.
        /// </summary>
        internal static string ManageLayoutCommandDefinition_Text {
            get {
                return ResourceManager.GetString("ManageLayoutCommandDefinition_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MultiLevel Redo.
        /// </summary>
        internal static string MultiRedoCommandDefinition_Name {
            get {
                return ResourceManager.GetString("MultiRedoCommandDefinition_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s.
        /// </summary>
        internal static string MultiRedoCommandDefinition_StatusSuffix {
            get {
                return ResourceManager.GetString("MultiRedoCommandDefinition_StatusSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo {0} Action{1}.
        /// </summary>
        internal static string MultiRedoCommandDefinition_StatusText {
            get {
                return ResourceManager.GetString("MultiRedoCommandDefinition_StatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Redo.
        /// </summary>
        internal static string MultiRedoCommandDefinition_Text {
            get {
                return ResourceManager.GetString("MultiRedoCommandDefinition_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        internal static string MultiRedoCommandDefinition_ToolTip {
            get {
                return ResourceManager.GetString("MultiRedoCommandDefinition_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MultiLevel Undo.
        /// </summary>
        internal static string MultiUndoCommandDefinition_Name {
            get {
                return ResourceManager.GetString("MultiUndoCommandDefinition_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s.
        /// </summary>
        internal static string MultiUndoCommandDefinition_StatusSuffix {
            get {
                return ResourceManager.GetString("MultiUndoCommandDefinition_StatusSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo {0} Action{1}.
        /// </summary>
        internal static string MultiUndoCommandDefinition_StatusText {
            get {
                return ResourceManager.GetString("MultiUndoCommandDefinition_StatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Undo.
        /// </summary>
        internal static string MultiUndoCommandDefinition_Text {
            get {
                return ResourceManager.GetString("MultiUndoCommandDefinition_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        internal static string MultiUndoCommandDefinition_ToolTip {
            get {
                return ResourceManager.GetString("MultiUndoCommandDefinition_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Options....
        /// </summary>
        internal static string OpenSettingsCommandDefinition_Text {
            get {
                return ResourceManager.GetString("OpenSettingsCommandDefinition_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Redo.
        /// </summary>
        internal static string RedoCommandDefinition_Text {
            get {
                return ResourceManager.GetString("RedoCommandDefinition_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SaveLayoutCommandDefinition_Name {
            get {
                return ResourceManager.GetString("SaveLayoutCommandDefinition_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SaveLayoutCommandDefinition_Text {
            get {
                return ResourceManager.GetString("SaveLayoutCommandDefinition_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SaveLayoutCommandDefinitionMessageBox_Default {
            get {
                return ResourceManager.GetString("SaveLayoutCommandDefinitionMessageBox_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SaveLayoutCommandDefinitionMessageBox_Label {
            get {
                return ResourceManager.GetString("SaveLayoutCommandDefinitionMessageBox_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SaveLayoutCommandDefinitionMessageBox_Title {
            get {
                return ResourceManager.GetString("SaveLayoutCommandDefinitionMessageBox_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window List.
        /// </summary>
        internal static string SwitchToDocumentCommandListDefinition_Name {
            get {
                return ResourceManager.GetString("SwitchToDocumentCommandListDefinition_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Undo.
        /// </summary>
        internal static string UndoCommandDefinition_Text {
            get {
                return ResourceManager.GetString("UndoCommandDefinition_Text", resourceCulture);
            }
        }
    }
}
