//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModernApplicationFramework.Extended.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Commands_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Commands_Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModernApplicationFramework.Extended.Properties.Commands.Resources", typeof(Commands_Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die E&amp;xit ähnelt.
        /// </summary>
        internal static string CloseProgammCommandDefinition_Text {
            get {
                return ResourceManager.GetString("CloseProgammCommandDefinition_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die F&amp;ull Screen ähnelt.
        /// </summary>
        internal static string FullScreenCommandDefinition_Text {
            get {
                return ResourceManager.GetString("FullScreenCommandDefinition_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MultiLevel Redo ähnelt.
        /// </summary>
        internal static string MultiRedoCommandDefinition_Name {
            get {
                return ResourceManager.GetString("MultiRedoCommandDefinition_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die s ähnelt.
        /// </summary>
        internal static string MultiRedoCommandDefinition_StatusSuffix {
            get {
                return ResourceManager.GetString("MultiRedoCommandDefinition_StatusSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Redo {0} Action{1} ähnelt.
        /// </summary>
        internal static string MultiRedoCommandDefinition_StatusText {
            get {
                return ResourceManager.GetString("MultiRedoCommandDefinition_StatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Redo ähnelt.
        /// </summary>
        internal static string MultiRedoCommandDefinition_Text {
            get {
                return ResourceManager.GetString("MultiRedoCommandDefinition_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Redo ähnelt.
        /// </summary>
        internal static string MultiRedoCommandDefinition_ToolTip {
            get {
                return ResourceManager.GetString("MultiRedoCommandDefinition_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MultiLevel Undo ähnelt.
        /// </summary>
        internal static string MultiUndoCommandDefinition_Name {
            get {
                return ResourceManager.GetString("MultiUndoCommandDefinition_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die s ähnelt.
        /// </summary>
        internal static string MultiUndoCommandDefinition_StatusSuffix {
            get {
                return ResourceManager.GetString("MultiUndoCommandDefinition_StatusSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Undo {0} Action{1} ähnelt.
        /// </summary>
        internal static string MultiUndoCommandDefinition_StatusText {
            get {
                return ResourceManager.GetString("MultiUndoCommandDefinition_StatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Undo ähnelt.
        /// </summary>
        internal static string MultiUndoCommandDefinition_Text {
            get {
                return ResourceManager.GetString("MultiUndoCommandDefinition_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Undo ähnelt.
        /// </summary>
        internal static string MultiUndoCommandDefinition_ToolTip {
            get {
                return ResourceManager.GetString("MultiUndoCommandDefinition_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Options... ähnelt.
        /// </summary>
        internal static string OpenSettingsCommandDefinition_Text {
            get {
                return ResourceManager.GetString("OpenSettingsCommandDefinition_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Redo ähnelt.
        /// </summary>
        internal static string RedoCommandDefinition_Text {
            get {
                return ResourceManager.GetString("RedoCommandDefinition_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string SaveLayoutCommandDefinition_Name {
            get {
                return ResourceManager.GetString("SaveLayoutCommandDefinition_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string SaveLayoutCommandDefinition_Text {
            get {
                return ResourceManager.GetString("SaveLayoutCommandDefinition_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string SaveLayoutCommandDefinitionMessageBox_Default {
            get {
                return ResourceManager.GetString("SaveLayoutCommandDefinitionMessageBox_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string SaveLayoutCommandDefinitionMessageBox_Label {
            get {
                return ResourceManager.GetString("SaveLayoutCommandDefinitionMessageBox_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string SaveLayoutCommandDefinitionMessageBox_Title {
            get {
                return ResourceManager.GetString("SaveLayoutCommandDefinitionMessageBox_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Window List ähnelt.
        /// </summary>
        internal static string SwitchToDocumentCommandListDefinition_Name {
            get {
                return ResourceManager.GetString("SwitchToDocumentCommandListDefinition_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Undo ähnelt.
        /// </summary>
        internal static string UndoCommandDefinition_Text {
            get {
                return ResourceManager.GetString("UndoCommandDefinition_Text", resourceCulture);
            }
        }
    }
}
