//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModernApplicationFramework.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class KeyboardLocalizationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal KeyboardLocalizationResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModernApplicationFramework.Properties.KeyboardLocalizationResources", typeof(KeyboardLocalizationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Num + ähnelt.
        /// </summary>
        public static string KeyboardKey_Add {
            get {
                return ResourceManager.GetString("KeyboardKey_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alt ähnelt.
        /// </summary>
        public static string KeyboardKey_Alt {
            get {
                return ResourceManager.GetString("KeyboardKey_Alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bkspce ähnelt.
        /// </summary>
        public static string KeyboardKey_Backspace {
            get {
                return ResourceManager.GetString("KeyboardKey_Backspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clear ähnelt.
        /// </summary>
        public static string KeyboardKey_Clear {
            get {
                return ResourceManager.GetString("KeyboardKey_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ctrl ähnelt.
        /// </summary>
        public static string KeyboardKey_Control {
            get {
                return ResourceManager.GetString("KeyboardKey_Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Num . ähnelt.
        /// </summary>
        public static string KeyboardKey_Decimal {
            get {
                return ResourceManager.GetString("KeyboardKey_Decimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Del ähnelt.
        /// </summary>
        public static string KeyboardKey_Delete {
            get {
                return ResourceManager.GetString("KeyboardKey_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Num / ähnelt.
        /// </summary>
        public static string KeyboardKey_Divide {
            get {
                return ResourceManager.GetString("KeyboardKey_Divide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Down Arrow ähnelt.
        /// </summary>
        public static string KeyboardKey_Down {
            get {
                return ResourceManager.GetString("KeyboardKey_Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die End ähnelt.
        /// </summary>
        public static string KeyboardKey_End {
            get {
                return ResourceManager.GetString("KeyboardKey_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter ähnelt.
        /// </summary>
        public static string KeyboardKey_Enter {
            get {
                return ResourceManager.GetString("KeyboardKey_Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Esc ähnelt.
        /// </summary>
        public static string KeyboardKey_Escape {
            get {
                return ResourceManager.GetString("KeyboardKey_Escape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die F1 ähnelt.
        /// </summary>
        public static string KeyboardKey_F1 {
            get {
                return ResourceManager.GetString("KeyboardKey_F1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die F10 ähnelt.
        /// </summary>
        public static string KeyboardKey_F10 {
            get {
                return ResourceManager.GetString("KeyboardKey_F10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die F11 ähnelt.
        /// </summary>
        public static string KeyboardKey_F11 {
            get {
                return ResourceManager.GetString("KeyboardKey_F11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die F12 ähnelt.
        /// </summary>
        public static string KeyboardKey_F12 {
            get {
                return ResourceManager.GetString("KeyboardKey_F12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die F13 ähnelt.
        /// </summary>
        public static string KeyboardKey_F13 {
            get {
                return ResourceManager.GetString("KeyboardKey_F13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die F14 ähnelt.
        /// </summary>
        public static string KeyboardKey_F14 {
            get {
                return ResourceManager.GetString("KeyboardKey_F14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die F15 ähnelt.
        /// </summary>
        public static string KeyboardKey_F15 {
            get {
                return ResourceManager.GetString("KeyboardKey_F15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die F16 ähnelt.
        /// </summary>
        public static string KeyboardKey_F16 {
            get {
                return ResourceManager.GetString("KeyboardKey_F16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die F17 ähnelt.
        /// </summary>
        public static string KeyboardKey_F17 {
            get {
                return ResourceManager.GetString("KeyboardKey_F17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die F18 ähnelt.
        /// </summary>
        public static string KeyboardKey_F18 {
            get {
                return ResourceManager.GetString("KeyboardKey_F18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die F19 ähnelt.
        /// </summary>
        public static string KeyboardKey_F19 {
            get {
                return ResourceManager.GetString("KeyboardKey_F19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die F2 ähnelt.
        /// </summary>
        public static string KeyboardKey_F2 {
            get {
                return ResourceManager.GetString("KeyboardKey_F2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die F20 ähnelt.
        /// </summary>
        public static string KeyboardKey_F20 {
            get {
                return ResourceManager.GetString("KeyboardKey_F20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die F21 ähnelt.
        /// </summary>
        public static string KeyboardKey_F21 {
            get {
                return ResourceManager.GetString("KeyboardKey_F21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die F22 ähnelt.
        /// </summary>
        public static string KeyboardKey_F22 {
            get {
                return ResourceManager.GetString("KeyboardKey_F22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die F23 ähnelt.
        /// </summary>
        public static string KeyboardKey_F23 {
            get {
                return ResourceManager.GetString("KeyboardKey_F23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die F24 ähnelt.
        /// </summary>
        public static string KeyboardKey_F24 {
            get {
                return ResourceManager.GetString("KeyboardKey_F24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die F3 ähnelt.
        /// </summary>
        public static string KeyboardKey_F3 {
            get {
                return ResourceManager.GetString("KeyboardKey_F3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die F4 ähnelt.
        /// </summary>
        public static string KeyboardKey_F4 {
            get {
                return ResourceManager.GetString("KeyboardKey_F4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die F5 ähnelt.
        /// </summary>
        public static string KeyboardKey_F5 {
            get {
                return ResourceManager.GetString("KeyboardKey_F5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die F6 ähnelt.
        /// </summary>
        public static string KeyboardKey_F6 {
            get {
                return ResourceManager.GetString("KeyboardKey_F6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die F7 ähnelt.
        /// </summary>
        public static string KeyboardKey_F7 {
            get {
                return ResourceManager.GetString("KeyboardKey_F7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die F8 ähnelt.
        /// </summary>
        public static string KeyboardKey_F8 {
            get {
                return ResourceManager.GetString("KeyboardKey_F8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die F9 ähnelt.
        /// </summary>
        public static string KeyboardKey_F9 {
            get {
                return ResourceManager.GetString("KeyboardKey_F9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ins ähnelt.
        /// </summary>
        public static string KeyboardKey_Insert {
            get {
                return ResourceManager.GetString("KeyboardKey_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Left Arrow ähnelt.
        /// </summary>
        public static string KeyboardKey_Left {
            get {
                return ResourceManager.GetString("KeyboardKey_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Left Windows ähnelt.
        /// </summary>
        public static string KeyboardKey_LeftWindows {
            get {
                return ResourceManager.GetString("KeyboardKey_LeftWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Num * ähnelt.
        /// </summary>
        public static string KeyboardKey_Multiplay {
            get {
                return ResourceManager.GetString("KeyboardKey_Multiplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Num 0 ähnelt.
        /// </summary>
        public static string KeyboardKey_NumPad0 {
            get {
                return ResourceManager.GetString("KeyboardKey_NumPad0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Num 1 ähnelt.
        /// </summary>
        public static string KeyboardKey_NumPad1 {
            get {
                return ResourceManager.GetString("KeyboardKey_NumPad1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Num 2 ähnelt.
        /// </summary>
        public static string KeyboardKey_NumPad2 {
            get {
                return ResourceManager.GetString("KeyboardKey_NumPad2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Num 3 ähnelt.
        /// </summary>
        public static string KeyboardKey_NumPad3 {
            get {
                return ResourceManager.GetString("KeyboardKey_NumPad3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Num 4 ähnelt.
        /// </summary>
        public static string KeyboardKey_NumPad4 {
            get {
                return ResourceManager.GetString("KeyboardKey_NumPad4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Num 5 ähnelt.
        /// </summary>
        public static string KeyboardKey_NumPad5 {
            get {
                return ResourceManager.GetString("KeyboardKey_NumPad5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Num 6 ähnelt.
        /// </summary>
        public static string KeyboardKey_NumPad6 {
            get {
                return ResourceManager.GetString("KeyboardKey_NumPad6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Num 7 ähnelt.
        /// </summary>
        public static string KeyboardKey_NumPad7 {
            get {
                return ResourceManager.GetString("KeyboardKey_NumPad7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Num 8 ähnelt.
        /// </summary>
        public static string KeyboardKey_NumPad8 {
            get {
                return ResourceManager.GetString("KeyboardKey_NumPad8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Num 9 ähnelt.
        /// </summary>
        public static string KeyboardKey_NumPad9 {
            get {
                return ResourceManager.GetString("KeyboardKey_NumPad9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PgDn ähnelt.
        /// </summary>
        public static string KeyboardKey_PageDown {
            get {
                return ResourceManager.GetString("KeyboardKey_PageDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PgUp ähnelt.
        /// </summary>
        public static string KeyboardKey_PageUp {
            get {
                return ResourceManager.GetString("KeyboardKey_PageUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Break ähnelt.
        /// </summary>
        public static string KeyboardKey_Pause {
            get {
                return ResourceManager.GetString("KeyboardKey_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Right Arrow ähnelt.
        /// </summary>
        public static string KeyboardKey_Right {
            get {
                return ResourceManager.GetString("KeyboardKey_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Right Windows ähnelt.
        /// </summary>
        public static string KeyboardKey_RightWindows {
            get {
                return ResourceManager.GetString("KeyboardKey_RightWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shift ähnelt.
        /// </summary>
        public static string KeyboardKey_Shift {
            get {
                return ResourceManager.GetString("KeyboardKey_Shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Space ähnelt.
        /// </summary>
        public static string KeyboardKey_Space {
            get {
                return ResourceManager.GetString("KeyboardKey_Space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Num - ähnelt.
        /// </summary>
        public static string KeyboardKey_Subtract {
            get {
                return ResourceManager.GetString("KeyboardKey_Subtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tab ähnelt.
        /// </summary>
        public static string KeyboardKey_Tab {
            get {
                return ResourceManager.GetString("KeyboardKey_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Up Arrow ähnelt.
        /// </summary>
        public static string KeyboardKey_Up {
            get {
                return ResourceManager.GetString("KeyboardKey_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Windows ähnelt.
        /// </summary>
        public static string KeyboardKey_Windows {
            get {
                return ResourceManager.GetString("KeyboardKey_Windows", resourceCulture);
            }
        }
    }
}
