//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModernApplicationFramework.Basics.Settings.General {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GeneralVisualExperienceSettingsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GeneralVisualExperienceSettingsResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModernApplicationFramework.Basics.Settings.General.GeneralVisualExperienceSetting" +
                            "sResources", typeof(GeneralVisualExperienceSettingsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Automatically adjust visual experience based on client performance ähnelt.
        /// </summary>
        public static string AutoAdjustVisualExperienceCheckBox_Text {
            get {
                return ResourceManager.GetString("AutoAdjustVisualExperienceCheckBox_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The visual experience settings automatically change based on system capabilities. ähnelt.
        /// </summary>
        public static string AutoAdjustVisualExperienceStatus {
            get {
                return ResourceManager.GetString("AutoAdjustVisualExperienceStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Color theme: ähnelt.
        /// </summary>
        public static string ColorThemeCombo_Label {
            get {
                return ResourceManager.GetString("ColorThemeCombo_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This application is currently using hardware-accelerated rendering. ähnelt.
        /// </summary>
        public static string HardwareRenderingStatus {
            get {
                return ResourceManager.GetString("HardwareRenderingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Enable rich client visual experience ähnelt.
        /// </summary>
        public static string RichClientVisualExperienceCheckBox_Text {
            get {
                return ResourceManager.GetString("RichClientVisualExperienceCheckBox_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This application is currently using software rendering. ähnelt.
        /// </summary>
        public static string SoftwareRendereingStatus {
            get {
                return ResourceManager.GetString("SoftwareRendereingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Use hardware graphics acceleration if available ähnelt.
        /// </summary>
        public static string UseHardwareAccelerationCheckBox_Text {
            get {
                return ResourceManager.GetString("UseHardwareAccelerationCheckBox_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Apply title case styling to _menu bar ähnelt.
        /// </summary>
        public static string UseTitleCaseMenuCheckBox_Text {
            get {
                return ResourceManager.GetString("UseTitleCaseMenuCheckBox_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Visual experience ähnelt.
        /// </summary>
        public static string VisualExperienceGroupBox {
            get {
                return ResourceManager.GetString("VisualExperienceGroupBox", resourceCulture);
            }
        }
    }
}
