//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModernApplicationFramework.Docking {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DockingResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DockingResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModernApplicationFramework.Docking.DockingResources", typeof(DockingResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy MDI Tool Window.
        /// </summary>
        public static string AnchorableAsDocumentContextMenu_Name {
            get {
                return ResourceManager.GetString("AnchorableAsDocumentContextMenu_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Docked Window.
        /// </summary>
        public static string AnchorableContextMenu_Name {
            get {
                return ResourceManager.GetString("AnchorableContextMenu_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A&amp;uto Hide All.
        /// </summary>
        public static string AutoHideAllWindowsCommandDefinition_Text {
            get {
                return ResourceManager.GetString("AutoHideAllWindowsCommandDefinition_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Auto Hide.
        /// </summary>
        public static string AutoHideWindowCommandDefinition_Text {
            get {
                return ResourceManager.GetString("AutoHideWindowCommandDefinition_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close All But This.
        /// </summary>
        public static string CloseAllButThisDockedWindowCommandDefinition_Text {
            get {
                return ResourceManager.GetString("CloseAllButThisDockedWindowCommandDefinition_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C&amp;lose All Documents.
        /// </summary>
        public static string CloseAllDockedWindowCommandDefinition_Text {
            get {
                return ResourceManager.GetString("CloseAllDockedWindowCommandDefinition_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CloseDockedWindowCommandDefinition_Text {
            get {
                return ResourceManager.GetString("CloseDockedWindowCommandDefinition_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dock as &amp;Tabbed Document.
        /// </summary>
        public static string DockAsTabbedDocumentCommandDefinition_Text {
            get {
                return ResourceManager.GetString("DockAsTabbedDocumentCommandDefinition_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doc&amp;k.
        /// </summary>
        public static string DockWindowCommandDefinition_Text {
            get {
                return ResourceManager.GetString("DockWindowCommandDefinition_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy MDI Document Window.
        /// </summary>
        public static string DocumentContextMenu_Name {
            get {
                return ResourceManager.GetString("DocumentContextMenu_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Float.
        /// </summary>
        public static string FloatDockedWindowCommandDefinition_Text {
            get {
                return ResourceManager.GetString("FloatDockedWindowCommandDefinition_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Hide.
        /// </summary>
        public static string HideDockedWindowCommandDefinition_Text {
            get {
                return ResourceManager.GetString("HideDockedWindowCommandDefinition_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move All to Next Tab Group.
        /// </summary>
        public static string MoveAllToNextTabGroupCommandDefinition_Text {
            get {
                return ResourceManager.GetString("MoveAllToNextTabGroupCommandDefinition_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move All to Previous Tab Group.
        /// </summary>
        public static string MoveAllToPreviousTabGroupCommandDefinition_Text {
            get {
                return ResourceManager.GetString("MoveAllToPreviousTabGroupCommandDefinition_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to Ne&amp;xt Tab Group.
        /// </summary>
        public static string MoveToNextTabGroupCommandDefinition_Text {
            get {
                return ResourceManager.GetString("MoveToNextTabGroupCommandDefinition_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to P&amp;revious Tab Group.
        /// </summary>
        public static string MoveToPreviousTabGroupCommandDefinition_Text {
            get {
                return ResourceManager.GetString("MoveToPreviousTabGroupCommandDefinition_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Hori&amp;zontal Tab Group.
        /// </summary>
        public static string NewHorizontalTabGroupCommandDefinition_Text {
            get {
                return ResourceManager.GetString("NewHorizontalTabGroupCommandDefinition_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New &amp;Vertical Tab Group.
        /// </summary>
        public static string NewVerticalTabGroupCommandDefinition_Text {
            get {
                return ResourceManager.GetString("NewVerticalTabGroupCommandDefinition_Text", resourceCulture);
            }
        }
    }
}
