//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModernApplicationFramework.Docking {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DockingResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DockingResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModernApplicationFramework.Docking.DockingResources", typeof(DockingResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Easy MDI Tool Window ähnelt.
        /// </summary>
        public static string AnchorableAsDocumentContextMenu_Name {
            get {
                return ResourceManager.GetString("AnchorableAsDocumentContextMenu_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Docked Window ähnelt.
        /// </summary>
        public static string AnchorableContextMenu_Name {
            get {
                return ResourceManager.GetString("AnchorableContextMenu_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A&amp;uto Hide All ähnelt.
        /// </summary>
        public static string AutoHideAllWindowsCommandDefinition_Text {
            get {
                return ResourceManager.GetString("AutoHideAllWindowsCommandDefinition_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Auto Hide ähnelt.
        /// </summary>
        public static string AutoHideWindowCommandDefinition_Text {
            get {
                return ResourceManager.GetString("AutoHideWindowCommandDefinition_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close All But This ähnelt.
        /// </summary>
        public static string CloseAllButThisDockedWindowCommandDefinition_Text {
            get {
                return ResourceManager.GetString("CloseAllButThisDockedWindowCommandDefinition_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die C&amp;lose All Documents ähnelt.
        /// </summary>
        public static string CloseAllDockedWindowCommandDefinition_Text {
            get {
                return ResourceManager.GetString("CloseAllDockedWindowCommandDefinition_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close ähnelt.
        /// </summary>
        public static string CloseDockedWindowCommandDefinition_Text {
            get {
                return ResourceManager.GetString("CloseDockedWindowCommandDefinition_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dock as &amp;Tabbed Document ähnelt.
        /// </summary>
        public static string DockAsTabbedDocumentCommandDefinition_Text {
            get {
                return ResourceManager.GetString("DockAsTabbedDocumentCommandDefinition_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Doc&amp;k ähnelt.
        /// </summary>
        public static string DockWindowCommandDefinition_Text {
            get {
                return ResourceManager.GetString("DockWindowCommandDefinition_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Easy MDI Document Window ähnelt.
        /// </summary>
        public static string DocumentContextMenu_Name {
            get {
                return ResourceManager.GetString("DocumentContextMenu_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Float ähnelt.
        /// </summary>
        public static string FloatDockedWindowCommandDefinition_Text {
            get {
                return ResourceManager.GetString("FloatDockedWindowCommandDefinition_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Hide ähnelt.
        /// </summary>
        public static string HideDockedWindowCommandDefinition_Text {
            get {
                return ResourceManager.GetString("HideDockedWindowCommandDefinition_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Move All to Next Tab Group ähnelt.
        /// </summary>
        public static string MoveAllToNextTabGroupCommandDefinition_Text {
            get {
                return ResourceManager.GetString("MoveAllToNextTabGroupCommandDefinition_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Move All to Previous Tab Group ähnelt.
        /// </summary>
        public static string MoveAllToPreviousTabGroupCommandDefinition_Text {
            get {
                return ResourceManager.GetString("MoveAllToPreviousTabGroupCommandDefinition_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Move to Ne&amp;xt Tab Group ähnelt.
        /// </summary>
        public static string MoveToNextTabGroupCommandDefinition_Text {
            get {
                return ResourceManager.GetString("MoveToNextTabGroupCommandDefinition_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Move to P&amp;revious Tab Group ähnelt.
        /// </summary>
        public static string MoveToPreviousTabGroupCommandDefinition_Text {
            get {
                return ResourceManager.GetString("MoveToPreviousTabGroupCommandDefinition_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New Hori&amp;zontal Tab Group ähnelt.
        /// </summary>
        public static string NewHorizontalTabGroupCommandDefinition_Text {
            get {
                return ResourceManager.GetString("NewHorizontalTabGroupCommandDefinition_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New &amp;Vertical Tab Group ähnelt.
        /// </summary>
        public static string NewVerticalTabGroupCommandDefinition_Text {
            get {
                return ResourceManager.GetString("NewVerticalTabGroupCommandDefinition_Text", resourceCulture);
            }
        }
    }
}
