//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MordernApplicationFramework.WindowManagement.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WindowManagement_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WindowManagement_Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MordernApplicationFramework.WindowManagement.Properties.WindowManagement.Resource" +
                            "s", typeof(WindowManagement_Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Are you sure you want to apply the layout &apos;{0}&apos; and discard your current window layout? ähnelt.
        /// </summary>
        internal static string ApplyLayoutConfirmation {
            get {
                return ResourceManager.GetString("ApplyLayoutConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not apply layout &apos;{0}&apos;. ähnelt.
        /// </summary>
        internal static string ApplyLayoutFailedMessage {
            get {
                return ResourceManager.GetString("ApplyLayoutFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Apply Window Layout ähnelt.
        /// </summary>
        internal static string ApplyLayoutTitle {
            get {
                return ResourceManager.GetString("ApplyLayoutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Apply Window Layout List ähnelt.
        /// </summary>
        internal static string ApplyWindowLayoutListCommandDefinition {
            get {
                return ResourceManager.GetString("ApplyWindowLayoutListCommandDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Are you sure you want to delete the layout &apos;{0}&apos;? ähnelt.
        /// </summary>
        internal static string DeleteLayoutConfirmation {
            get {
                return ResourceManager.GetString("DeleteLayoutConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete Window Layout ähnelt.
        /// </summary>
        internal static string DeleteLayoutTitle {
            get {
                return ResourceManager.GetString("DeleteLayoutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Don&apos;t show me this message again ähnelt.
        /// </summary>
        internal static string DisableApplyLayoutWarning {
            get {
                return ResourceManager.GetString("DisableApplyLayoutWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A layout named &apos;{0}&apos; already exists.
        ///Do you want to replace it? ähnelt.
        /// </summary>
        internal static string LayoutOverwriteMessage {
            get {
                return ResourceManager.GetString("LayoutOverwriteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string ManageLayoutCommandDefinition_Name {
            get {
                return ResourceManager.GetString("ManageLayoutCommandDefinition_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string ManageLayoutCommandDefinition_Text {
            get {
                return ResourceManager.GetString("ManageLayoutCommandDefinition_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close ähnelt.
        /// </summary>
        internal static string ManageLayoutsButton_Close {
            get {
                return ResourceManager.GetString("ManageLayoutsButton_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Delete ähnelt.
        /// </summary>
        internal static string ManageLayoutsButton_Delete {
            get {
                return ResourceManager.GetString("ManageLayoutsButton_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Rename ähnelt.
        /// </summary>
        internal static string ManageLayoutsButton_Rename {
            get {
                return ResourceManager.GetString("ManageLayoutsButton_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Move Down (Alt+Down) ähnelt.
        /// </summary>
        internal static string ManageLayoutsButtonTooltip_IndexDown {
            get {
                return ResourceManager.GetString("ManageLayoutsButtonTooltip_IndexDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Move Up (Alt+Up) ähnelt.
        /// </summary>
        internal static string ManageLayoutsButtonTooltip_IndexUp {
            get {
                return ResourceManager.GetString("ManageLayoutsButtonTooltip_IndexUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Saved layouts: ähnelt.
        /// </summary>
        internal static string ManageLayoutsDialogSavedLayouts {
            get {
                return ResourceManager.GetString("ManageLayoutsDialogSavedLayouts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Manage Window Layouts ähnelt.
        /// </summary>
        internal static string ManageLayoutsDialogTitle {
            get {
                return ResourceManager.GetString("ManageLayoutsDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Apply Window Layout ähnelt.
        /// </summary>
        internal static string MenuDefinition_ApplyLayout {
            get {
                return ResourceManager.GetString("MenuDefinition_ApplyLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No Saved Layouts ähnelt.
        /// </summary>
        internal static string NoSavedLayouts {
            get {
                return ResourceManager.GetString("NoSavedLayouts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Layout name: ähnelt.
        /// </summary>
        internal static string RenameLayoutMessage {
            get {
                return ResourceManager.GetString("RenameLayoutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rename Window Layout ähnelt.
        /// </summary>
        internal static string RenameLayoutTitle {
            get {
                return ResourceManager.GetString("RenameLayoutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save Window Layout ähnelt.
        /// </summary>
        internal static string SaveLayoutCommandDefinition_Name {
            get {
                return ResourceManager.GetString("SaveLayoutCommandDefinition_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string SaveLayoutCommandDefinition_Text {
            get {
                return ResourceManager.GetString("SaveLayoutCommandDefinition_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New Layout {0} ähnelt.
        /// </summary>
        internal static string SaveLayoutCommandDefinitionMessageBox_Default {
            get {
                return ResourceManager.GetString("SaveLayoutCommandDefinitionMessageBox_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Layout name: ähnelt.
        /// </summary>
        internal static string SaveLayoutCommandDefinitionMessageBox_Label {
            get {
                return ResourceManager.GetString("SaveLayoutCommandDefinitionMessageBox_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save Window Layout ähnelt.
        /// </summary>
        internal static string SaveLayoutCommandDefinitionMessageBox_Title {
            get {
                return ResourceManager.GetString("SaveLayoutCommandDefinitionMessageBox_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Window layout &quot;{0}&quot; successfully saved. ähnelt.
        /// </summary>
        internal static string SaveLayoutCompletedStatusFormat {
            get {
                return ResourceManager.GetString("SaveLayoutCompletedStatusFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die We could not save your layout. The total number of layouts reached maximum of {0}.
        ///
        ///Please delete one or more layouts before saving. ähnelt.
        /// </summary>
        internal static string SaveLayoutErrorMaxLayoutsReached {
            get {
                return ResourceManager.GetString("SaveLayoutErrorMaxLayoutsReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not save window layout &quot;{0}&quot;. ähnelt.
        /// </summary>
        internal static string SaveLayoutErrorStatusFormat {
            get {
                return ResourceManager.GetString("SaveLayoutErrorStatusFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Saving window layout &quot;{0}&quot;... ähnelt.
        /// </summary>
        internal static string SaveLayoutStartedStatusFormat {
            get {
                return ResourceManager.GetString("SaveLayoutStartedStatusFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save Window Layout ähnelt.
        /// </summary>
        internal static string SaveLayoutTitle {
            get {
                return ResourceManager.GetString("SaveLayoutTitle", resourceCulture);
            }
        }
    }
}
