//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MordernApplicationFramework.WindowManagement.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WindowManagement_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WindowManagement_Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MordernApplicationFramework.WindowManagement.Properties.WindowManagement.Resource" +
                            "s", typeof(WindowManagement_Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string ApplyLayoutConfirmation {
            get {
                return ResourceManager.GetString("ApplyLayoutConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string ApplyLayoutConformation {
            get {
                return ResourceManager.GetString("ApplyLayoutConformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string ApplyLayoutFailedMessage {
            get {
                return ResourceManager.GetString("ApplyLayoutFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Apply Window Layout ähnelt.
        /// </summary>
        internal static string ApplyLayoutTitle {
            get {
                return ResourceManager.GetString("ApplyLayoutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string DeleteLayoutConfirmation {
            get {
                return ResourceManager.GetString("DeleteLayoutConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string DeleteLayoutTitle {
            get {
                return ResourceManager.GetString("DeleteLayoutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string DisableApplyLayoutWarning {
            get {
                return ResourceManager.GetString("DisableApplyLayoutWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string LayoutOverwriteMessage {
            get {
                return ResourceManager.GetString("LayoutOverwriteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fensterlayouts verwalten ähnelt.
        /// </summary>
        internal static string ManageLayoutCommandDefinition_Name {
            get {
                return ResourceManager.GetString("ManageLayoutCommandDefinition_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fensterlayouts &amp;verwalten ähnelt.
        /// </summary>
        internal static string ManageLayoutCommandDefinition_Text {
            get {
                return ResourceManager.GetString("ManageLayoutCommandDefinition_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string RenameLayoutMessage {
            get {
                return ResourceManager.GetString("RenameLayoutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string RenameLayoutTitle {
            get {
                return ResourceManager.GetString("RenameLayoutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save Window Layout ähnelt.
        /// </summary>
        internal static string SaveLayoutCommandDefinition_Name {
            get {
                return ResourceManager.GetString("SaveLayoutCommandDefinition_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string SaveLayoutCommandDefinition_Text {
            get {
                return ResourceManager.GetString("SaveLayoutCommandDefinition_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New Layout {0} ähnelt.
        /// </summary>
        internal static string SaveLayoutCommandDefinitionMessageBox_Default {
            get {
                return ResourceManager.GetString("SaveLayoutCommandDefinitionMessageBox_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Layout name: ähnelt.
        /// </summary>
        internal static string SaveLayoutCommandDefinitionMessageBox_Label {
            get {
                return ResourceManager.GetString("SaveLayoutCommandDefinitionMessageBox_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save Window Layout ähnelt.
        /// </summary>
        internal static string SaveLayoutCommandDefinitionMessageBox_Title {
            get {
                return ResourceManager.GetString("SaveLayoutCommandDefinitionMessageBox_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string SaveLayoutTitle {
            get {
                return ResourceManager.GetString("SaveLayoutTitle", resourceCulture);
            }
        }
    }
}
