//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModernApplicationFramework.Modules.Toolbox.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ChooseItemsDialogResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ChooseItemsDialogResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModernApplicationFramework.Modules.Toolbox.Resources.ChooseItemsDialogResources", typeof(ChooseItemsDialogResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly Name.
        /// </summary>
        public static string AllToolboxItemsPageInfo_ColumnAssembly {
            get {
                return ResourceManager.GetString("AllToolboxItemsPageInfo_ColumnAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string AllToolboxItemsPageInfo_ColumnName {
            get {
                return ResourceManager.GetString("AllToolboxItemsPageInfo_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespace.
        /// </summary>
        public static string AllToolboxItemsPageInfo_ColumnNamespace {
            get {
                return ResourceManager.GetString("AllToolboxItemsPageInfo_ColumnNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string AllToolboxItemsPageInfo_ColumnVersion {
            get {
                return ResourceManager.GetString("AllToolboxItemsPageInfo_ColumnVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Toolbox Items.
        /// </summary>
        public static string AllToolboxItemsPageInfo_Name {
            get {
                return ResourceManager.GetString("AllToolboxItemsPageInfo_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applying Changes.
        /// </summary>
        public static string ApplyingChangesString {
            get {
                return ResourceManager.GetString("ApplyingChangesString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ChooseItemsDialogCancel {
            get {
                return ResourceManager.GetString("ChooseItemsDialogCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string ChooseItemsDialogOk {
            get {
                return ResourceManager.GetString("ChooseItemsDialogOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Reset.
        /// </summary>
        public static string ChooseItemsDialogReset {
            get {
                return ResourceManager.GetString("ChooseItemsDialogReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Toolbox Items.
        /// </summary>
        public static string ChooseItemsDialogTitle {
            get {
                return ResourceManager.GetString("ChooseItemsDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly:.
        /// </summary>
        public static string ChooseItemsPage_LabelAssembly {
            get {
                return ResourceManager.GetString("ChooseItemsPage_LabelAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Filter.
        /// </summary>
        public static string ChooseItemsPage_LabelFilter {
            get {
                return ResourceManager.GetString("ChooseItemsPage_LabelFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (none).
        /// </summary>
        public static string ChooseItemsPage_LabelNone {
            get {
                return ResourceManager.GetString("ChooseItemsPage_LabelNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        public static string ChooseItemsPage_LabelVersion {
            get {
                return ResourceManager.GetString("ChooseItemsPage_LabelVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading items....
        /// </summary>
        public static string ChooseItemsPage_LoadingItems {
            get {
                return ResourceManager.GetString("ChooseItemsPage_LoadingItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Clear.
        /// </summary>
        public static string ChooseItemsPageDelete {
            get {
                return ResourceManager.GetString("ChooseItemsPageDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string InvisibleItemsDialog_OK {
            get {
                return ResourceManager.GetString("InvisibleItemsDialog_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure the controls to add are compatible with the current window content..
        /// </summary>
        public static string InvisibleItemsDialog_TextLower {
            get {
                return ResourceManager.GetString("InvisibleItemsDialog_TextLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following controls were successfully added to the toolbox but are not enabled in the active window content:.
        /// </summary>
        public static string InvisibleItemsDialog_TextUpper {
            get {
                return ResourceManager.GetString("InvisibleItemsDialog_TextUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolbox.
        /// </summary>
        public static string InvisibleItemsDialog_Title {
            get {
                return ResourceManager.GetString("InvisibleItemsDialog_Title", resourceCulture);
            }
        }
    }
}
