//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModernApplicationFramework.Modules.Toolbox.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ToolboxResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ToolboxResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModernApplicationFramework.Modules.Toolbox.Resources.ToolboxResources", typeof(ToolboxResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolbox Add Tab.
        /// </summary>
        public static string AddCategoryCommand_Name {
            get {
                return ResourceManager.GetString("AddCategoryCommand_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Add Tab.
        /// </summary>
        public static string AddCategoryCommand_Text {
            get {
                return ResourceManager.GetString("AddCategoryCommand_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/Remove Toolbox Items.
        /// </summary>
        public static string AddItemCommand_Name {
            get {
                return ResourceManager.GetString("AddItemCommand_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose &amp;Items....
        /// </summary>
        public static string AddItemCommand_Text {
            get {
                return ResourceManager.GetString("AddItemCommand_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string DefaultCategoryName {
            get {
                return ResourceManager.GetString("DefaultCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolbox Delete Tab.
        /// </summary>
        public static string DeleteCategoryCommand_Name {
            get {
                return ResourceManager.GetString("DeleteCategoryCommand_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $Delete Tab.
        /// </summary>
        public static string DeleteCategoryCommand_Text {
            get {
                return ResourceManager.GetString("DeleteCategoryCommand_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab name &apos;{0}&apos; already exists..
        /// </summary>
        public static string Error_Duplicate {
            get {
                return ResourceManager.GetString("Error_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caption cannot be empty..
        /// </summary>
        public static string Error_NameEmpty {
            get {
                return ResourceManager.GetString("Error_NameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolbox Rename Tab.
        /// </summary>
        public static string RenameCategoryCommand_Name {
            get {
                return ResourceManager.GetString("RenameCategoryCommand_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Rename Tab.
        /// </summary>
        public static string RenameCategoryCommand_Text {
            get {
                return ResourceManager.GetString("RenameCategoryCommand_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolbox Rename Item.
        /// </summary>
        public static string RenameItemCommand_Name {
            get {
                return ResourceManager.GetString("RenameItemCommand_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Rename Item.
        /// </summary>
        public static string RenameItemCommand_Text {
            get {
                return ResourceManager.GetString("RenameItemCommand_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Toolbox.
        /// </summary>
        public static string ResetToolboxCommand_Name {
            get {
                return ResourceManager.GetString("ResetToolboxCommand_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R&amp;eset Toolbox.
        /// </summary>
        public static string ResetToolboxCommand_Text {
            get {
                return ResourceManager.GetString("ResetToolboxCommand_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolbox Show All.
        /// </summary>
        public static string ShowAllNodesCommand_Name {
            get {
                return ResourceManager.GetString("ShowAllNodesCommand_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Show All.
        /// </summary>
        public static string ShowAllNodesCommand_Text {
            get {
                return ResourceManager.GetString("ShowAllNodesCommand_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolbox Sort Items.
        /// </summary>
        public static string SortItemsAlphabeticallyCommand_Name {
            get {
                return ResourceManager.GetString("SortItemsAlphabeticallyCommand_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S&amp;ort Items Alphabetically.
        /// </summary>
        public static string SortItemsAlphabeticallyCommand_Text {
            get {
                return ResourceManager.GetString("SortItemsAlphabeticallyCommand_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolbox.
        /// </summary>
        public static string ToolboxCommandName {
            get {
                return ResourceManager.GetString("ToolboxCommandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no usable controls in this group. Drag an item onto this text to add it to the toolbox..
        /// </summary>
        public static string ToolboxEmptyMessage {
            get {
                return ResourceManager.GetString("ToolboxEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; will be removed from the Toolbox..
        /// </summary>
        public static string ToolboxItemDeleteMessage {
            get {
                return ResourceManager.GetString("ToolboxItemDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolbox Move Tab Down.
        /// </summary>
        public static string ToolboxNodeDownCommand_Name {
            get {
                return ResourceManager.GetString("ToolboxNodeDownCommand_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Do&amp;wn.
        /// </summary>
        public static string ToolboxNodeDownCommand_Text {
            get {
                return ResourceManager.GetString("ToolboxNodeDownCommand_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolbox Move Tab Up.
        /// </summary>
        public static string ToolboxNodeUpCommand_Name {
            get {
                return ResourceManager.GetString("ToolboxNodeUpCommand_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move &amp;Up.
        /// </summary>
        public static string ToolboxNodeUpCommand_Text {
            get {
                return ResourceManager.GetString("ToolboxNodeUpCommand_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolbox default settings will be restored. All custom Toolbox items will be removed.\r\n\r\nContinue?.
        /// </summary>
        public static string ToolboxResetMessage {
            get {
                return ResourceManager.GetString("ToolboxResetMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results found..
        /// </summary>
        public static string ToolboxSearchNoResults {
            get {
                return ResourceManager.GetString("ToolboxSearchNoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Toolbox.
        /// </summary>
        public static string ToolboxSearchWatermark {
            get {
                return ResourceManager.GetString("ToolboxSearchWatermark", resourceCulture);
            }
        }
    }
}
