//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModernApplicationFramework.Modules.Toolbox {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ToolboxResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ToolboxResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModernApplicationFramework.Modules.Toolbox.ToolboxResources", typeof(ToolboxResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Toolbox Add Tab ähnelt.
        /// </summary>
        public static string AddCategoryCommand_Name {
            get {
                return ResourceManager.GetString("AddCategoryCommand_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Add Tab ähnelt.
        /// </summary>
        public static string AddCategoryCommand_Text {
            get {
                return ResourceManager.GetString("AddCategoryCommand_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die General ähnelt.
        /// </summary>
        public static string DefaultCategoryName {
            get {
                return ResourceManager.GetString("DefaultCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Toolbox Delete Tab ähnelt.
        /// </summary>
        public static string DeleteCategoryCommand_Name {
            get {
                return ResourceManager.GetString("DeleteCategoryCommand_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die $Delete Tab ähnelt.
        /// </summary>
        public static string DeleteCategoryCommand_Text {
            get {
                return ResourceManager.GetString("DeleteCategoryCommand_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tab name &apos;{0}&apos; already exists. ähnelt.
        /// </summary>
        public static string Error_Duplicate {
            get {
                return ResourceManager.GetString("Error_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Caption cannot be empty. ähnelt.
        /// </summary>
        public static string Error_NameEmpty {
            get {
                return ResourceManager.GetString("Error_NameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Toolbox Rename Tab ähnelt.
        /// </summary>
        public static string RenameCategoryCommand_Name {
            get {
                return ResourceManager.GetString("RenameCategoryCommand_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Rename Tab ähnelt.
        /// </summary>
        public static string RenameCategoryCommand_Text {
            get {
                return ResourceManager.GetString("RenameCategoryCommand_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Toolbox Rename Item ähnelt.
        /// </summary>
        public static string RenameItemCommand_Name {
            get {
                return ResourceManager.GetString("RenameItemCommand_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Rename Item ähnelt.
        /// </summary>
        public static string RenameItemCommand_Text {
            get {
                return ResourceManager.GetString("RenameItemCommand_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reset Toolbox ähnelt.
        /// </summary>
        public static string ResetToolboxCommand_Name {
            get {
                return ResourceManager.GetString("ResetToolboxCommand_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die R&amp;eset Toolbox ähnelt.
        /// </summary>
        public static string ResetToolboxCommand_Text {
            get {
                return ResourceManager.GetString("ResetToolboxCommand_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Toolbox Show All ähnelt.
        /// </summary>
        public static string ShowAllNodesCommand_Name {
            get {
                return ResourceManager.GetString("ShowAllNodesCommand_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Show All ähnelt.
        /// </summary>
        public static string ShowAllNodesCommand_Text {
            get {
                return ResourceManager.GetString("ShowAllNodesCommand_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Toolbox Sort Items ähnelt.
        /// </summary>
        public static string SortItemsAlphabeticallyCommand_Name {
            get {
                return ResourceManager.GetString("SortItemsAlphabeticallyCommand_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die S&amp;ort Items Alphabetically ähnelt.
        /// </summary>
        public static string SortItemsAlphabeticallyCommand_Text {
            get {
                return ResourceManager.GetString("SortItemsAlphabeticallyCommand_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Toolbox ähnelt.
        /// </summary>
        public static string ToolboxCommandName {
            get {
                return ResourceManager.GetString("ToolboxCommandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There are no usable controls in this group. Drag an item onto this text to add it to the toolbox. ähnelt.
        /// </summary>
        public static string ToolboxEmptyMessage {
            get {
                return ResourceManager.GetString("ToolboxEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &apos;{0}&apos; will be removed from the Toolbox. ähnelt.
        /// </summary>
        public static string ToolboxItemDeleteMessage {
            get {
                return ResourceManager.GetString("ToolboxItemDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Toolbox Move Tab Down ähnelt.
        /// </summary>
        public static string ToolboxNodeDownCommand_Name {
            get {
                return ResourceManager.GetString("ToolboxNodeDownCommand_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Move Do&amp;wn ähnelt.
        /// </summary>
        public static string ToolboxNodeDownCommand_Text {
            get {
                return ResourceManager.GetString("ToolboxNodeDownCommand_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Toolbox Move Tab Up ähnelt.
        /// </summary>
        public static string ToolboxNodeUpCommand_Name {
            get {
                return ResourceManager.GetString("ToolboxNodeUpCommand_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Move &amp;Up ähnelt.
        /// </summary>
        public static string ToolboxNodeUpCommand_Text {
            get {
                return ResourceManager.GetString("ToolboxNodeUpCommand_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No results found. ähnelt.
        /// </summary>
        public static string ToolboxSearchNoResults {
            get {
                return ResourceManager.GetString("ToolboxSearchNoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Search Toolbox ähnelt.
        /// </summary>
        public static string ToolboxSearchWatermark {
            get {
                return ResourceManager.GetString("ToolboxSearchWatermark", resourceCulture);
            }
        }
    }
}
