//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModernApplicationFramework.Extended.Settings.General {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GeneralVisualExperienceSettingsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GeneralVisualExperienceSettingsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModernApplicationFramework.Extended.Settings.General.GeneralVisualExperienceSetti" +
                            "ngsResources", typeof(GeneralVisualExperienceSettingsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Automatically adjust visual experience based on client performance.
        /// </summary>
        public static string AutoAdjustVisualExperienceCheckBox_Text {
            get {
                return ResourceManager.GetString("AutoAdjustVisualExperienceCheckBox_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  The visual experience settings automatically change based on system capabilities..
        /// </summary>
        public static string AutoAdjustVisualExperienceStatus {
            get {
                return ResourceManager.GetString("AutoAdjustVisualExperienceStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Color theme:.
        /// </summary>
        public static string ColorThemeCombo_Label {
            get {
                return ResourceManager.GetString("ColorThemeCombo_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application is currently using hardware-accelerated rendering..
        /// </summary>
        public static string HardwareRenderingStatus {
            get {
                return ResourceManager.GetString("HardwareRenderingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Enable rich client visual experience.
        /// </summary>
        public static string RichClientVisualExperienceCheckBox_Text {
            get {
                return ResourceManager.GetString("RichClientVisualExperienceCheckBox_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application is currently using software rendering..
        /// </summary>
        public static string SoftwareRendereingStatus {
            get {
                return ResourceManager.GetString("SoftwareRendereingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Use hardware graphics acceleration if available.
        /// </summary>
        public static string UseHardwareAccelerationCheckBox_Text {
            get {
                return ResourceManager.GetString("UseHardwareAccelerationCheckBox_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply title case styling to _menu bar.
        /// </summary>
        public static string UseTitleCaseMenuCheckBox_Text {
            get {
                return ResourceManager.GetString("UseTitleCaseMenuCheckBox_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual experience.
        /// </summary>
        public static string VisualExperienceGroupBox {
            get {
                return ResourceManager.GetString("VisualExperienceGroupBox", resourceCulture);
            }
        }
    }
}
