//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModernApplicationFramework.Extended.Settings.Keyboard {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class KeyboardSettingsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal KeyboardSettingsResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModernApplicationFramework.Extended.Settings.Keyboard.KeyboardSettingsResources", typeof(KeyboardSettingsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A_ssign ähnelt.
        /// </summary>
        public static string KeyboardSettingsApplyNewBinding_Button {
            get {
                return ResourceManager.GetString("KeyboardSettingsApplyNewBinding_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shortcut c_urrently used by: ähnelt.
        /// </summary>
        public static string KeyboardSettingsCurrentBindings_Label {
            get {
                return ResourceManager.GetString("KeyboardSettingsCurrentBindings_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Press shortcut keys: ähnelt.
        /// </summary>
        public static string KeyboardSettingsNewBinding_Label {
            get {
                return ResourceManager.GetString("KeyboardSettingsNewBinding_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use _new shortcut in: ähnelt.
        /// </summary>
        public static string KeyboardSettingsNewBindingCategory_Label {
            get {
                return ResourceManager.GetString("KeyboardSettingsNewBindingCategory_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Remove ähnelt.
        /// </summary>
        public static string KeyboardSettingsRemoveCurrentBinding_Button {
            get {
                return ResourceManager.GetString("KeyboardSettingsRemoveCurrentBinding_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show _commands containing: ähnelt.
        /// </summary>
        public static string KeyboardSettingsSearch_Label {
            get {
                return ResourceManager.GetString("KeyboardSettingsSearch_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shor_tcuts for selected command: ähnelt.
        /// </summary>
        public static string KeyboardSettingsSelectedBinding_Label {
            get {
                return ResourceManager.GetString("KeyboardSettingsSelectedBinding_Label", resourceCulture);
            }
        }
    }
}
