//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModernApplicationFramework.EditorBase.CommandBar.Resources {
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommandsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommandsResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModernApplicationFramework.EditorBase.CommandBar.Resources.CommandsResources", typeof(CommandsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copy Full Path ähnelt.
        /// </summary>
        public static string CopyFullPathCommandText {
            get {
                return ResourceManager.GetString("CopyFullPathCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;File... ähnelt.
        /// </summary>
        public static string NewFileCommandText {
            get {
                return ResourceManager.GetString("NewFileCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open Containing Folder ähnelt.
        /// </summary>
        public static string OpenContainingFolderCommandText {
            get {
                return ResourceManager.GetString("OpenContainingFolderCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;File... ähnelt.
        /// </summary>
        public static string OpenFileCommandText {
            get {
                return ResourceManager.GetString("OpenFileCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Recent File List ähnelt.
        /// </summary>
        public static string RecentFileListCommand {
            get {
                return ResourceManager.GetString("RecentFileListCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No entries in list ähnelt.
        /// </summary>
        public static string RecentFileListCommand_NoItems {
            get {
                return ResourceManager.GetString("RecentFileListCommand_NoItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save Selected Items &amp;As... ähnelt.
        /// </summary>
        public static string SaveActiveDocumentAsCommandName {
            get {
                return ResourceManager.GetString("SaveActiveDocumentAsCommandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save {0} &amp;As... ähnelt.
        /// </summary>
        public static string SaveActiveDocumentAsCommandText {
            get {
                return ResourceManager.GetString("SaveActiveDocumentAsCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Save Selected Items ähnelt.
        /// </summary>
        public static string SaveActiveDocumentCommandName {
            get {
                return ResourceManager.GetString("SaveActiveDocumentCommandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Save {0} ähnelt.
        /// </summary>
        public static string SaveActiveDocumentCommandText {
            get {
                return ResourceManager.GetString("SaveActiveDocumentCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save A&amp;ll ähnelt.
        /// </summary>
        public static string SaveAllCommandText {
            get {
                return ResourceManager.GetString("SaveAllCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Windows... ähnelt.
        /// </summary>
        public static string WindowSelectCommandText {
            get {
                return ResourceManager.GetString("WindowSelectCommandText", resourceCulture);
            }
        }
    }
}
