//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModernApplicationFramework.Extended.Settings.Keyboard {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class KeyboardSettingsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal KeyboardSettingsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModernApplicationFramework.Extended.Settings.Keyboard.KeyboardSettingsResources", typeof(KeyboardSettingsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard.
        /// </summary>
        public static string KeyboardSettings_Name {
            get {
                return ResourceManager.GetString("KeyboardSettings_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A_ssign.
        /// </summary>
        public static string KeyboardSettingsApplyNewBinding_Button {
            get {
                return ResourceManager.GetString("KeyboardSettingsApplyNewBinding_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply the following additional keyboard _mapping scheme:.
        /// </summary>
        public static string KeyboardSettingsApplyScheme_Label {
            get {
                return ResourceManager.GetString("KeyboardSettingsApplyScheme_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut c_urrently used by:.
        /// </summary>
        public static string KeyboardSettingsCurrentBindings_Label {
            get {
                return ResourceManager.GetString("KeyboardSettingsCurrentBindings_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Press shortcut keys:.
        /// </summary>
        public static string KeyboardSettingsNewBinding_Label {
            get {
                return ResourceManager.GetString("KeyboardSettingsNewBinding_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use _new shortcut in:.
        /// </summary>
        public static string KeyboardSettingsNewBindingCategory_Label {
            get {
                return ResourceManager.GetString("KeyboardSettingsNewBindingCategory_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Remove.
        /// </summary>
        public static string KeyboardSettingsRemoveCurrentBinding_Button {
            get {
                return ResourceManager.GetString("KeyboardSettingsRemoveCurrentBinding_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R_eset.
        /// </summary>
        public static string KeyboardSettingsResetScheme {
            get {
                return ResourceManager.GetString("KeyboardSettingsResetScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show _commands containing:.
        /// </summary>
        public static string KeyboardSettingsSearch_Label {
            get {
                return ResourceManager.GetString("KeyboardSettingsSearch_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shor_tcuts for selected command:.
        /// </summary>
        public static string KeyboardSettingsSelectedBinding_Label {
            get {
                return ResourceManager.GetString("KeyboardSettingsSelectedBinding_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard mappings will reset to their default values. Continue?.
        /// </summary>
        public static string KeyboardSettingsWarningApplyScheme {
            get {
                return ResourceManager.GetString("KeyboardSettingsWarningApplyScheme", resourceCulture);
            }
        }
    }
}
