//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModernApplicationFramework.EditorBase.NewElementDialog {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NewElementDialogResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NewElementDialogResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModernApplicationFramework.EditorBase.NewElementDialog.NewElementDialogResources", typeof(NewElementDialogResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Browse....
        /// </summary>
        public static string NewElementBrowseButton {
            get {
                return ResourceManager.GetString("NewElementBrowseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string NewElementCancelButton {
            get {
                return ResourceManager.GetString("NewElementCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Destination:.
        /// </summary>
        public static string NewElementDestinationLabel {
            get {
                return ResourceManager.GetString("NewElementDestinationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        public static string NewElementDetailsTypeLabel {
            get {
                return ResourceManager.GetString("NewElementDetailsTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Name:.
        /// </summary>
        public static string NewElementNameLabel {
            get {
                return ResourceManager.GetString("NewElementNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string NewElementOkButton {
            get {
                return ResourceManager.GetString("NewElementOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open.
        /// </summary>
        public static string NewElementOpenButton {
            get {
                return ResourceManager.GetString("NewElementOpenButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string NewElementOpenButtonItem {
            get {
                return ResourceManager.GetString("NewElementOpenButtonItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open with....
        /// </summary>
        public static string NewElementOpenWithButtonItem {
            get {
                return ResourceManager.GetString("NewElementOpenWithButtonItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by:.
        /// </summary>
        public static string NewElementSortByLabel {
            get {
                return ResourceManager.GetString("NewElementSortByLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string NewElementSortDefault {
            get {
                return ResourceManager.GetString("NewElementSortDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name (ascending).
        /// </summary>
        public static string NewElementSortNameAsc {
            get {
                return ResourceManager.GetString("NewElementSortNameAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name (descending).
        /// </summary>
        public static string NewElementSortNameDesc {
            get {
                return ResourceManager.GetString("NewElementSortNameDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New File.
        /// </summary>
        public static string NewFileDialogWindowTitle {
            get {
                return ResourceManager.GetString("NewFileDialogWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file templates found.
        /// </summary>
        public static string NewFileExtensionMessageNoItems {
            get {
                return ResourceManager.GetString("NewFileExtensionMessageNoItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No item selected.
        /// </summary>
        public static string NewFileExtensionMessageNoSelectedItem {
            get {
                return ResourceManager.GetString("NewFileExtensionMessageNoSelectedItem", resourceCulture);
            }
        }
    }
}
