//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModernApplicationFramework.EditorBase.Commands {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommandsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommandsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModernApplicationFramework.EditorBase.Commands.CommandsResources", typeof(CommandsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Full Path.
        /// </summary>
        public static string CopyFullPathCommandText {
            get {
                return ResourceManager.GetString("CopyFullPathCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;File....
        /// </summary>
        public static string NewFileCommandText {
            get {
                return ResourceManager.GetString("NewFileCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Containing Folder.
        /// </summary>
        public static string OpenContainingFolderCommandText {
            get {
                return ResourceManager.GetString("OpenContainingFolderCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;File....
        /// </summary>
        public static string OpenFileCommandText {
            get {
                return ResourceManager.GetString("OpenFileCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Selected Items &amp;As....
        /// </summary>
        public static string SaveActiveDocumentAsCommandName {
            get {
                return ResourceManager.GetString("SaveActiveDocumentAsCommandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save {0} &amp;As....
        /// </summary>
        public static string SaveActiveDocumentAsCommandText {
            get {
                return ResourceManager.GetString("SaveActiveDocumentAsCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Save Selected Items.
        /// </summary>
        public static string SaveActiveDocumentCommandName {
            get {
                return ResourceManager.GetString("SaveActiveDocumentCommandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Save {0}.
        /// </summary>
        public static string SaveActiveDocumentCommandText {
            get {
                return ResourceManager.GetString("SaveActiveDocumentCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save A&amp;ll.
        /// </summary>
        public static string SaveAllCommandText {
            get {
                return ResourceManager.GetString("SaveAllCommandText", resourceCulture);
            }
        }
    }
}
