//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModernApplicationFramework.Basics.CustomizeDialog {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Customize_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Customize_Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModernApplicationFramework.Basics.CustomizeDialog.Customize.Resources", typeof(Customize_Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cate_gories.
        /// </summary>
        public static string AddCommandPrompt_Categories {
            get {
                return ResourceManager.GetString("AddCommandPrompt_Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comman_ds:.
        /// </summary>
        public static string AddCommandPrompt_Commands {
            get {
                return ResourceManager.GetString("AddCommandPrompt_Commands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the command to add and click OK..
        /// </summary>
        public static string AddCommandPrompt_InfoText {
            get {
                return ResourceManager.GetString("AddCommandPrompt_InfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add command.
        /// </summary>
        public static string AddCommandPrompt_Title {
            get {
                return ResourceManager.GetString("AddCommandPrompt_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Add Command....
        /// </summary>
        public static string CommandsPage_AddCommand {
            get {
                return ResourceManager.GetString("CommandsPage_AddCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add N_ew Menu....
        /// </summary>
        public static string CommandsPage_AddNewMenu {
            get {
                return ResourceManager.GetString("CommandsPage_AddNewMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin a _Group.
        /// </summary>
        public static string CommandsPage_BeginGroup {
            get {
                return ResourceManager.GetString("CommandsPage_BeginGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a menu or toolbar to rearrange:.
        /// </summary>
        public static string CommandsPage_ComboGroupHeader {
            get {
                return ResourceManager.GetString("CommandsPage_ComboGroupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conte_xt menu:.
        /// </summary>
        public static string CommandsPage_ContextMenuGroupItem {
            get {
                return ResourceManager.GetString("CommandsPage_ContextMenuGroupItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defa_ult style.
        /// </summary>
        public static string CommandsPage_DefaultStyle {
            get {
                return ResourceManager.GetString("CommandsPage_DefaultStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Delete.
        /// </summary>
        public static string CommandsPage_Delete {
            get {
                return ResourceManager.GetString("CommandsPage_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image _and Text.
        /// </summary>
        public static string CommandsPage_ImageAndText {
            get {
                return ResourceManager.GetString("CommandsPage_ImageAndText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Controls.
        /// </summary>
        public static string CommandsPage_ListBoxHeader {
            get {
                return ResourceManager.GetString("CommandsPage_ListBoxHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu _bar:.
        /// </summary>
        public static string CommandsPage_MenuBarGroupItem {
            get {
                return ResourceManager.GetString("CommandsPage_MenuBarGroupItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Modify Selection.
        /// </summary>
        public static string CommandsPage_ModifySelection {
            get {
                return ResourceManager.GetString("CommandsPage_ModifySelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Dow_n.
        /// </summary>
        public static string CommandsPage_MoveDown {
            get {
                return ResourceManager.GetString("CommandsPage_MoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move _Up.
        /// </summary>
        public static string CommandsPage_MoveUp {
            get {
                return ResourceManager.GetString("CommandsPage_MoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Name:.
        /// </summary>
        public static string CommandsPage_Name {
            get {
                return ResourceManager.GetString("CommandsPage_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Reset.
        /// </summary>
        public static string CommandsPage_Reset {
            get {
                return ResourceManager.GetString("CommandsPage_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset All.
        /// </summary>
        public static string CommandsPage_ResetAll {
            get {
                return ResourceManager.GetString("CommandsPage_ResetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Text Only (Always).
        /// </summary>
        public static string CommandsPage_TextOnlyAlways {
            get {
                return ResourceManager.GetString("CommandsPage_TextOnlyAlways", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text _Only (in Menus).
        /// </summary>
        public static string CommandsPage_TextOnlyMenu {
            get {
                return ResourceManager.GetString("CommandsPage_TextOnlyMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Toolbar:.
        /// </summary>
        public static string CommandsPage_ToolbarGroupItem {
            get {
                return ResourceManager.GetString("CommandsPage_ToolbarGroupItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Width:.
        /// </summary>
        public static string CommandsPage_Width {
            get {
                return ResourceManager.GetString("CommandsPage_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C_ommands.
        /// </summary>
        public static string CustomizeDialog_Commands {
            get {
                return ResourceManager.GetString("CustomizeDialog_Commands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize.
        /// </summary>
        public static string CustomizeDialog_Title {
            get {
                return ResourceManager.GetString("CustomizeDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolbar_s.
        /// </summary>
        public static string CustomizeDialog_Toolbars {
            get {
                return ResourceManager.GetString("CustomizeDialog_Toolbars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The toolbar name cannot be blank. Type a name..
        /// </summary>
        public static string Error_AddOrRenameToolbarEmptyName {
            get {
                return ResourceManager.GetString("Error_AddOrRenameToolbarEmptyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A toolbar named &quot;{0}&quot; already exists. Type another name..
        /// </summary>
        public static string Error_AddOrRenameToolbarExisting {
            get {
                return ResourceManager.GetString("Error_AddOrRenameToolbarExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The width must be a positive integer value or 0 to use default width..
        /// </summary>
        public static string Error_InvalidComboBoxWidthValue {
            get {
                return ResourceManager.GetString("Error_InvalidComboBoxWidthValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command name cannot be blank. Type a name..
        /// </summary>
        public static string Error_RenameCommandEmptyName {
            get {
                return ResourceManager.GetString("Error_RenameCommandEmptyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewToolbar.
        /// </summary>
        public static string NewToolbarPrompt_Title {
            get {
                return ResourceManager.GetString("NewToolbarPrompt_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolbar _name:.
        /// </summary>
        public static string NewToolbarPrompt_ToolbarName {
            get {
                return ResourceManager.GetString("NewToolbarPrompt_ToolbarName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Prompt_Cancel {
            get {
                return ResourceManager.GetString("Prompt_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Prompt_Close {
            get {
                return ResourceManager.GetString("Prompt_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Prompt_Ok {
            get {
                return ResourceManager.GetString("Prompt_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to reset the changes made to the &quot;{0}&quot; context menu?.
        /// </summary>
        public static string Prompt_ResetContextMenuConfirmation {
            get {
                return ResourceManager.GetString("Prompt_ResetContextMenuConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to reset the changes made to the &quot;{0}&quot; menu?.
        /// </summary>
        public static string Prompt_ResetMenuConfirmation {
            get {
                return ResourceManager.GetString("Prompt_ResetMenuConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to reset the changes made to the &quot;{0}&quot; toolbar?.
        /// </summary>
        public static string Prompt_ResetToolBarConfirmation {
            get {
                return ResourceManager.GetString("Prompt_ResetToolBarConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the &quot;{0}&quot; toolbar?.
        /// </summary>
        public static string Prompt_ToolbarDeleteConfirmation {
            get {
                return ResourceManager.GetString("Prompt_ToolbarDeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Delete.
        /// </summary>
        public static string ToolbarsPage_DeleteToolbar {
            get {
                return ResourceManager.GetString("ToolbarsPage_DeleteToolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dock location: _Bottom.
        /// </summary>
        public static string ToolbarsPage_DockLocationButtom {
            get {
                return ResourceManager.GetString("ToolbarsPage_DockLocationButtom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dock location: _Left.
        /// </summary>
        public static string ToolbarsPage_DockLocationLeft {
            get {
                return ResourceManager.GetString("ToolbarsPage_DockLocationLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dock location: _Right.
        /// </summary>
        public static string ToolbarsPage_DockLocationRight {
            get {
                return ResourceManager.GetString("ToolbarsPage_DockLocationRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dock location: _Top.
        /// </summary>
        public static string ToolbarsPage_DockLocationTop {
            get {
                return ResourceManager.GetString("ToolbarsPage_DockLocationTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolb_ars:.
        /// </summary>
        public static string ToolbarsPage_ListBoxTitle {
            get {
                return ResourceManager.GetString("ToolbarsPage_ListBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Modify Selection.
        /// </summary>
        public static string ToolbarsPage_ModifyToolbar {
            get {
                return ResourceManager.GetString("ToolbarsPage_ModifyToolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _New....
        /// </summary>
        public static string ToolbarsPage_NewToolbar {
            get {
                return ResourceManager.GetString("ToolbarsPage_NewToolbar", resourceCulture);
            }
        }
    }
}
