//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModernApplicationFramework.Input.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class KeyboardLocalizationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal KeyboardLocalizationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModernApplicationFramework.Input.Resources.KeyboardLocalizationResources", typeof(KeyboardLocalizationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Num +.
        /// </summary>
        public static string KeyboardKey_Add {
            get {
                return ResourceManager.GetString("KeyboardKey_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt.
        /// </summary>
        public static string KeyboardKey_Alt {
            get {
                return ResourceManager.GetString("KeyboardKey_Alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bkspce.
        /// </summary>
        public static string KeyboardKey_Backspace {
            get {
                return ResourceManager.GetString("KeyboardKey_Backspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string KeyboardKey_Clear {
            get {
                return ResourceManager.GetString("KeyboardKey_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl.
        /// </summary>
        public static string KeyboardKey_Control {
            get {
                return ResourceManager.GetString("KeyboardKey_Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Num ..
        /// </summary>
        public static string KeyboardKey_Decimal {
            get {
                return ResourceManager.GetString("KeyboardKey_Decimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Del.
        /// </summary>
        public static string KeyboardKey_Delete {
            get {
                return ResourceManager.GetString("KeyboardKey_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Num /.
        /// </summary>
        public static string KeyboardKey_Divide {
            get {
                return ResourceManager.GetString("KeyboardKey_Divide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down Arrow.
        /// </summary>
        public static string KeyboardKey_Down {
            get {
                return ResourceManager.GetString("KeyboardKey_Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string KeyboardKey_End {
            get {
                return ResourceManager.GetString("KeyboardKey_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        public static string KeyboardKey_Enter {
            get {
                return ResourceManager.GetString("KeyboardKey_Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esc.
        /// </summary>
        public static string KeyboardKey_Escape {
            get {
                return ResourceManager.GetString("KeyboardKey_Escape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F1.
        /// </summary>
        public static string KeyboardKey_F1 {
            get {
                return ResourceManager.GetString("KeyboardKey_F1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F10.
        /// </summary>
        public static string KeyboardKey_F10 {
            get {
                return ResourceManager.GetString("KeyboardKey_F10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F11.
        /// </summary>
        public static string KeyboardKey_F11 {
            get {
                return ResourceManager.GetString("KeyboardKey_F11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F12.
        /// </summary>
        public static string KeyboardKey_F12 {
            get {
                return ResourceManager.GetString("KeyboardKey_F12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F13.
        /// </summary>
        public static string KeyboardKey_F13 {
            get {
                return ResourceManager.GetString("KeyboardKey_F13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F14.
        /// </summary>
        public static string KeyboardKey_F14 {
            get {
                return ResourceManager.GetString("KeyboardKey_F14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F15.
        /// </summary>
        public static string KeyboardKey_F15 {
            get {
                return ResourceManager.GetString("KeyboardKey_F15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F16.
        /// </summary>
        public static string KeyboardKey_F16 {
            get {
                return ResourceManager.GetString("KeyboardKey_F16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F17.
        /// </summary>
        public static string KeyboardKey_F17 {
            get {
                return ResourceManager.GetString("KeyboardKey_F17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F18.
        /// </summary>
        public static string KeyboardKey_F18 {
            get {
                return ResourceManager.GetString("KeyboardKey_F18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F19.
        /// </summary>
        public static string KeyboardKey_F19 {
            get {
                return ResourceManager.GetString("KeyboardKey_F19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F2.
        /// </summary>
        public static string KeyboardKey_F2 {
            get {
                return ResourceManager.GetString("KeyboardKey_F2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F20.
        /// </summary>
        public static string KeyboardKey_F20 {
            get {
                return ResourceManager.GetString("KeyboardKey_F20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F21.
        /// </summary>
        public static string KeyboardKey_F21 {
            get {
                return ResourceManager.GetString("KeyboardKey_F21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F22.
        /// </summary>
        public static string KeyboardKey_F22 {
            get {
                return ResourceManager.GetString("KeyboardKey_F22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F23.
        /// </summary>
        public static string KeyboardKey_F23 {
            get {
                return ResourceManager.GetString("KeyboardKey_F23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F24.
        /// </summary>
        public static string KeyboardKey_F24 {
            get {
                return ResourceManager.GetString("KeyboardKey_F24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F3.
        /// </summary>
        public static string KeyboardKey_F3 {
            get {
                return ResourceManager.GetString("KeyboardKey_F3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F4.
        /// </summary>
        public static string KeyboardKey_F4 {
            get {
                return ResourceManager.GetString("KeyboardKey_F4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F5.
        /// </summary>
        public static string KeyboardKey_F5 {
            get {
                return ResourceManager.GetString("KeyboardKey_F5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F6.
        /// </summary>
        public static string KeyboardKey_F6 {
            get {
                return ResourceManager.GetString("KeyboardKey_F6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F7.
        /// </summary>
        public static string KeyboardKey_F7 {
            get {
                return ResourceManager.GetString("KeyboardKey_F7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F8.
        /// </summary>
        public static string KeyboardKey_F8 {
            get {
                return ResourceManager.GetString("KeyboardKey_F8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F9.
        /// </summary>
        public static string KeyboardKey_F9 {
            get {
                return ResourceManager.GetString("KeyboardKey_F9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ins.
        /// </summary>
        public static string KeyboardKey_Insert {
            get {
                return ResourceManager.GetString("KeyboardKey_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Arrow.
        /// </summary>
        public static string KeyboardKey_Left {
            get {
                return ResourceManager.GetString("KeyboardKey_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Windows.
        /// </summary>
        public static string KeyboardKey_LeftWindows {
            get {
                return ResourceManager.GetString("KeyboardKey_LeftWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Num *.
        /// </summary>
        public static string KeyboardKey_Multiplay {
            get {
                return ResourceManager.GetString("KeyboardKey_Multiplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Num 0.
        /// </summary>
        public static string KeyboardKey_NumPad0 {
            get {
                return ResourceManager.GetString("KeyboardKey_NumPad0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Num 1.
        /// </summary>
        public static string KeyboardKey_NumPad1 {
            get {
                return ResourceManager.GetString("KeyboardKey_NumPad1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Num 2.
        /// </summary>
        public static string KeyboardKey_NumPad2 {
            get {
                return ResourceManager.GetString("KeyboardKey_NumPad2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Num 3.
        /// </summary>
        public static string KeyboardKey_NumPad3 {
            get {
                return ResourceManager.GetString("KeyboardKey_NumPad3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Num 4.
        /// </summary>
        public static string KeyboardKey_NumPad4 {
            get {
                return ResourceManager.GetString("KeyboardKey_NumPad4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Num 5.
        /// </summary>
        public static string KeyboardKey_NumPad5 {
            get {
                return ResourceManager.GetString("KeyboardKey_NumPad5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Num 6.
        /// </summary>
        public static string KeyboardKey_NumPad6 {
            get {
                return ResourceManager.GetString("KeyboardKey_NumPad6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Num 7.
        /// </summary>
        public static string KeyboardKey_NumPad7 {
            get {
                return ResourceManager.GetString("KeyboardKey_NumPad7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Num 8.
        /// </summary>
        public static string KeyboardKey_NumPad8 {
            get {
                return ResourceManager.GetString("KeyboardKey_NumPad8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Num 9.
        /// </summary>
        public static string KeyboardKey_NumPad9 {
            get {
                return ResourceManager.GetString("KeyboardKey_NumPad9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PgDn.
        /// </summary>
        public static string KeyboardKey_PageDown {
            get {
                return ResourceManager.GetString("KeyboardKey_PageDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PgUp.
        /// </summary>
        public static string KeyboardKey_PageUp {
            get {
                return ResourceManager.GetString("KeyboardKey_PageUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Break.
        /// </summary>
        public static string KeyboardKey_Pause {
            get {
                return ResourceManager.GetString("KeyboardKey_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Arrow.
        /// </summary>
        public static string KeyboardKey_Right {
            get {
                return ResourceManager.GetString("KeyboardKey_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Windows.
        /// </summary>
        public static string KeyboardKey_RightWindows {
            get {
                return ResourceManager.GetString("KeyboardKey_RightWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift.
        /// </summary>
        public static string KeyboardKey_Shift {
            get {
                return ResourceManager.GetString("KeyboardKey_Shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space.
        /// </summary>
        public static string KeyboardKey_Space {
            get {
                return ResourceManager.GetString("KeyboardKey_Space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Num -.
        /// </summary>
        public static string KeyboardKey_Subtract {
            get {
                return ResourceManager.GetString("KeyboardKey_Subtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab.
        /// </summary>
        public static string KeyboardKey_Tab {
            get {
                return ResourceManager.GetString("KeyboardKey_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up Arrow.
        /// </summary>
        public static string KeyboardKey_Up {
            get {
                return ResourceManager.GetString("KeyboardKey_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows.
        /// </summary>
        public static string KeyboardKey_Windows {
            get {
                return ResourceManager.GetString("KeyboardKey_Windows", resourceCulture);
            }
        }
    }
}
